use_frameworks!

platform :ios, '9.0'

target 'RNLibreToolsiOS15_Example' do
  pod 'RNLibreToolsiOS15', :path => '../'

  target 'RNLibreToolsiOS15_Tests' do
    inherit! :search_paths

    
  end
end
